version: '3.7'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    networks:
      - slurm
    environment:
      MYSQL_DATABASE: slurm
      MYSQL_USER: slurm
      MYSQL_PASSWORD: slurm
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - var_lib_mysql:/var/lib/mysql

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    depends_on:
      - mysql
    container_name: slurm-db
    hostname: slurm-db
    networks:
      - slurm

  controller:
    build:
      context: .
      dockerfile: ./controller/Dockerfile
    depends_on:
      - database
      - etcd
    container_name: slurm-controller
    hostname: slurm-controller
    networks:
      - slurm
    environment:
      ETCDCTL_API: 3
      ETCD_ENDPOINTS: etcd:2379
    volumes:
      - ./jobs:/data

  worker01:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - controller
    container_name: slurm-worker1
    hostname: slurm-worker1
    networks:
      - slurm

  worker02:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - controller
    container_name: slurm-worker2
    hostname: slurm-worker2
    networks:
      - slurm

  etcd:
    image: quay.io/coreos/etcd:v3.3.15
    command: etcd --name etcd --data-dir=/etcd-data --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster 'etcd=http://etcd:2380'
    hostname: etcd
    container_name: etcd
    networks:
      - slurm
    volumes:
      - etcd_data:/etcd-data
    expose:
      - "2379"

  fakebuffernode:
    hostname: fakebuffernode
    container_name: fakebuffernode
    # scale: 1
    build:
      context: .
      dockerfile: ./buffernode/Dockerfile
    environment:
      DAC_SKIP_ANSIBLE: "True"
      ETCDCTL_API: 3
      ETCDCTL_ENDPOINTS: etcd:2379
      DEVICE_COUNT: 2
    networks:
      - slurm
    depends_on:
      - etcd

networks:
  slurm:
volumes:
  var_lib_mysql:
  etcd_data:
